site_name: OONI-Research 網路干預開放觀察計畫
site_url: https://ooni-research.ocf.tw/docs/
site_description: OONI Probe and ASNs finding in Taiwan.
site_author: OCF OONI-Research Volunteer
repo_url: https://github.com/ocftw/ooni-research
repo_name: ocftw/ooni-research
edit_uri: https://github.com/ocftw/ooni-research/blob/main/docs/docs/
copyright: "CC-BY 4.0 2023-2025 OCF OONI-Research Project"
nav:
  - index.md
  - what-is-ooni.md
  - 網路自由為什麼重要？: internet-freedem.md
  - 參與專案:
      - ASNs 自治網路觀測資料分析: ooni-asns-coverage.md
      - OONI 網站檢測清單: ooni-weblists.md
      - 中文化與文件翻譯: ooni-i18n.md
  - blog/index.md
  - 近期活動: events.md
theme:
  name: material
  icon:
    logo: material/database-search-outline
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.svg
  font:
    text: "Roboto"
    code: "Noto Sans Mono"
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  language: zh-TW
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.view
    - content.action.edit
    - content.tooltips
extra:
  alternate:
    - name: 台灣正體（zh-TW）
      link: /docs/zh-tw/
      lang: zh-TW
    - name: English (en-US)
      link: /docs/en-us/
      lang: en-us
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      lang:
        - zh
        - en
  - social:
      cards_layout: default/invert
      cards_layout_options:
        font_family: Noto Sans TC
        color: "#ffffff"
        background_color: "#0287cf"
  - privacy
  - git-revision-date-localized:
      type: iso_datetime
      locale: en
      enable_creation_date: true
  - blog
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
