name: BuildDocs

on:
  push:
    branches:
      - "docs"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-24.04"]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update libs
        run: sudo apt-get update
      - name: Install ca
        run: sudo apt-get install ca-certificates
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Sync Packages
        run: uv sync --group=dev
      - name: Show packages
        run: uv tree
      - name: Install mkdocs-material social dependencies
        run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Build Docs (/)
        run: source ./.venv/bin/activate; sh ./run.sh;
      - name: Replaces og
        run: cd output/assets/images/social/blog/posts; wget https://s3.toomore.net/ocf/tor-pre-event-zh-tw.png -O ./rightscon25-pre-event.png;
      - name: Build Docs (/zh-tw)
        run: source ./.venv/bin/activate; sh ./run_zh-tw.sh;
      - name: Build Docs (/zh-cn)
        run: source ./.venv/bin/activate; sh ./run_zh-cn.sh;
      - name: Replaces og
        run: cd output/zh-tw/assets/images/social/blog/posts; wget https://s3.toomore.net/ocf/tor-pre-event-zh-tw.png -O ./rightscon25-pre-event.png;
      - name: Build Docs (/en)
        run: source ./.venv/bin/activate; sh ./run_en.sh;
      - name: Replaces og
        run: cd output/en/assets/images/social/blog/posts; wget https://s3.toomore.net/ocf/tor-pre-event.png -O ./rightscon25-pre-event.png;
      - name: Replaces og
        run: cd output/assets/images/social/blog/posts; cp ../../../../../blog/assets/images/g0v-hackath65n.webp ./g0v-hackath65n.png;
      - name: Replaces og (/zh-tw)
        run: cd output/zh-tw/assets/images/social/blog/posts; cp ../../../../../blog/assets/images/g0v-hackath65n.webp ./g0v-hackath65n.png;
      - name: Replaces og
        run: cd output/assets/images/social/blog/posts; cp ../../../../../blog/assets/images/tor-tails-workshop-slide.webp ./rightscon25-tor-tails-ooni-after.png;
      - name: Replaces og (/zh-tw)
        run: cd output/zh-tw/assets/images/social/blog/posts; cp ../../../../../blog/assets/images/tor-tails-workshop-slide.webp ./rightscon25-tor-tails-ooni-after.png;
      - name: Replaces og (/en)
        run: cd output/en/assets/images/social/blog/posts; cp ../../../../../blog/assets/images/tor-tails-workshop-slide.webp ./rightscon25-tor-tails-ooni-after.png;
      - name: Clean the all files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOC_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_S3_KEY }}
        run: source ./.venv/bin/activate; aws s3 rm s3://${{ secrets.DOC_BUCKET }}/docs --recursive
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOC_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_S3_KEY }}
        run: source ./.venv/bin/activate; aws s3 sync ./output s3://${{ secrets.DOC_BUCKET }}/docs/ --acl public-read
