name: RIPE ASNname Lists
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '20 0 * * *'

jobs:
  check_list:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./asn_coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update libs
        run: sudo apt-get update
      - name: Install certificates
        run: sudo apt-get install ca-certificates
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install -v
      - name: Show packages
        run: poetry show --tree
      - name: Run Download ASN Lists (ALL)
        run: poetry run python3 ./ripe.py list
      - name: Run Download ASN Lists (TW)
        run: poetry run python3 ./ripe.py list --loc TW
