name: RIPE ASNname Lists
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "20 0 * * *"

jobs:
  check_list:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./asn_coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update libs
        run: sudo apt-get update
      - name: Install certificates
        run: sudo apt-get install ca-certificates
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Show Python Version
        run: cat .python-version
      - name: Show packages
        run: uv tree
      - name: Run Download ASN Lists (ALL)
        run: uv run ./ripe.py list
      - name: Run Download ASN Lists (TW)
        run: uv run ./ripe.py list --loc TW
