name: Lookback OONI Data
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "20 0 * * *"

jobs:
  check_list:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./asn_coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update libs
        run: sudo apt-get update
      - name: Install certificates
        run: sudo apt-get install ca-certificates
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Sync Packages
        run: uv sync
      - name: Show packages
        run: uv tree
      - name: Run Lookback OONI Data TW
        run: uv run ./ooni.py lookback --units=36 --loc=TW
      - name: Run Lookback OONI Data JP
        run: uv run ./ooni.py lookback --units=36 --loc=JP
      - name: Run Lookback OONI Data HK
        run: uv run ./ooni.py lookback --units=36 --loc=HK
      - name: Run Lookback OONI Data CN
        run: uv run ./ooni.py lookback --units=36 --loc=CN
