name: Lookback OONI Data
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "20 0 * * *"

jobs:
  check_list:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./asn_coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update libs
        run: sudo apt-get update
      - name: Install certificates
        run: sudo apt-get install ca-certificates
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install -v
      - name: Show packages
        run: poetry show --tree
      - name: Run Lookback OONI Data TW
        run: poetry run python3 ./ooni.py lookback --units=36 --loc=TW
      - name: Run Lookback OONI Data JP
        run: poetry run python3 ./ooni.py lookback --units=36 --loc=JP
      - name: Run Lookback OONI Data HK
        run: poetry run python3 ./ooni.py lookback --units=36 --loc=HK
      - name: Run Lookback OONI Data CN
        run: poetry run python3 ./ooni.py lookback --units=36 --loc=CN
